spring:
  datasource:
    url: jdbc:mysql://192.168.146.10:3306/springboot?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      access-to-underlying-connection-allowed: true




person:
  name: '周三'
  age: 20
server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
    accesslog:
      encoding: UTF-8


mybatis:
  mapperLocations: classpath:mapper/*.xml
  #  config-location: classpath:mybatis-config.xml
  typeAliasesPackage: com.cgb.springboot.domain
  ## Mybatis
#  mybatis.type-aliases-package=com.cgb.springboot.domain
logging:
  level:
    root: debug
    sun:
      rmi: info
    org:
      springframework: info
      apache: info
      mybatis: info
    com:
      cgb: debug
      zaxxer: info
  pattern: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%nn'
#  mybatis.mapper-locations=classpath:mapper/*.xml